# Generated by Django 2.2.4 on 2019-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.TextField()),
                ('company', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=250)),
            ],
        ),
    ]
